project('order-cache', 'cpp',
  version : '0.1',
  default_options : ['warning_level=3', 'cpp_std=c++17'])

executable('order-cache',
           'main.cpp',
           install : true)

executable('stress-test',
           'stress_test.cpp',
           install : true)

executable('test-binary',
           'test_binary.cpp',
           install : true)
